version: '3.6'

services:
  api:
    build: .
    depends_on:
      - db
    environment:
      STAGE: test
      FLASK_ENV: production
      FLASK_DEBUG: 0
      SQLALCHEMY_DATABASE_URI: postgresql://test:test@db/customerdb
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    restart: always

  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: customerdb
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data