"""empty message

Revision ID: 85dbd6501643
Revises: 8dd60bfea935
Create Date: 2020-06-09 12:59:32.441302

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '85dbd6501643'
down_revision = '8dd60bfea935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'dob',
                    existing_type=sa.DATE(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'dob',
                    existing_type=sa.DATE(),
                    nullable=True)
    # ### end Alembic commands ###
